language: node_js
os:
  - 'linux'
node_js:
  - '16'
branches:
  only:
  - '/.*/'
install:
    - yarn
cache:
  directories:
  - node_modules
script:
    - yarn install
    - yarn build
